ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.sivadevops.in
REDIS_HOST: redis-dev.sivadevops.in
CATALOGUE_HOST: catalogue-dev.sivadevops.in
USER_HOST: user-dev.sivadevops.in
CART_HOST: cart-dev.sivadevops.in
MYSQL_HOST: mysql-dev.sivadevops.in
SHIPPING_HOST: shipping-dev.sivadevops.in
RABBITMQ_HOST: rabbitmq-dev.sivadevops.in
PAYMENT_HOST: payment-dev.sivadevops.in