ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-"{{env}}".sivadevops.in
REDIS_HOST: redis-"{{env}}".sivadevops.in
CATALOGUE_HOST: catalogue-"{{env}}".sivadevops.in
USER_HOST: user-"{{env}}".sivadevops.in
CART_HOST: cart-"{{env}}".sivadevops.in
MYSQL_HOST: mysql-"{{env}}".sivadevops.in
SHIPPING_HOST: shipping-"{{env}}".sivadevops.in
RABBITMQ_HOST: rabbitmq-"{{env}}".sivadevops.in
PAYMENT_HOST: payment-"{{env}}".sivadevops.in