ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{env}}.sivadevops.in
REDIS_HOST: redis-{{env}}.sivadevops.in
CATALOGUE_HOST: catalogue.backend-alb-{{env}}.sivadevops.in
USER_HOST: user.backend-alb-{{env}}.sivadevops.in
CART_HOST: cart.backend-alb-{{env}}.sivadevops.in
MYSQL_HOST: mysql-{{env}}.sivadevops.in
SHIPPING_HOST: shipping.backend-alb-{{env}}.sivadevops.in
RABBITMQ_HOST: rabbitmq-{{env}}.sivadevops.in
PAYMENT_HOST: payment.backend-alb-{{env}}.sivadevops.in
app_version: v3